// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lahilqkjgrlpmduqpluk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhaGlscWtqZ3JscG1kdXFwbHVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODk4OTQsImV4cCI6MjA2OTE2NTg5NH0.H8i6rT1XAzk7MK5ptuRgurlw43-j2PBy22W8mMpo4bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});